# django blog service
apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080

---

# django blog deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django-blog
          image: django-blog:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis-svc  # Redis 服务的名字
            - name: REDIS_PORT
              value: "6379"  # Redis 默认端口
            - name: REDIS_PASSWORD
              value: "123qwe"  # Redis 密码（如果有）
            - name: DATABASE_HOST
              value: mysql-svc  # 数据库服务的名字
            - name: DATABASE_NAME
              value: mydb
            - name: DATABASE_USER
              value: root
            - name: DATABASE_PASSWORD
              value: password

