services: 
  django: 
    build: .
    volumes:
      - static_volume:/app/staticfiles   # 把 staticfiles 映射出来
    ports: 
      - "8000:8000"

  nginx:
    image: nginx:alpine
    volumes:
      - static_volume:/app/staticfiles   # 和 django 共享静态文件
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  static_volume:

