services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor
    restart: unless-stopped


  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitor
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=123qwe123???
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped

  redis_exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis://117.72.175.93:30082"
      REDIS_PASSWORD: "123qwe"
    networks:
      - monitor
    restart: unless-stopped
  
  mysql_exporter:
    image: prom/mysqld-exporter:v0.16.0
    container_name: mysql_exporter
    ports:
      - "9104:9104"
    command:
      - "--mysqld.username=exporter_user:password"
      - "--mysqld.address=117.72.175.93:30081"
    networks:
      - monitor

volumes:
  grafana-data:

networks:
  monitor:
