name: Test Django Blog

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Docker network
        run: docker network create network_test || true

      - name: Run MySQL
        run: |
          docker run -d --name mysql --network network_test \
            -e MYSQL_ROOT_PASSWORD=root \
            -e MYSQL_DATABASE=mydb \
            -e MYSQL_USER=test_user \
            -e MYSQL_PASSWORD=test_pass \
            mysql:8

      - name: Run Redis
        run: |
          docker run -d --name redis --network network_test redis:7

      - name: Wait for MySQL
        run: |
          until docker exec mysql mysqladmin ping -h "localhost" --silent; do
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Build the Docker image
        run: docker build -t django-blog-test:latest django/

      - name: Run Django Blog container
        run: |
          # 启动容器并检查数据库配置以及启动配置
          docker run -d --network network_test \
            --name django_demo \
            -e DATABASE_HOST=mysql \
            -e DATABASE_PORT=3306 \
            -e DATABASE_USER=test_user \
            -e DATABASE_PASSWORD=test_pass \
            -e DATABASE_NAME=mydb \
            -e REDIS_HOST=redis \
            -e REDIS_PORT=6379 \
            django-blog-test:latest /bin/bash -c \
            "python -u manage.py migrate --check; python -u manage.py check"

      - name: Cat Django Blog logs
        run: docker logs django_demo
